README.md, document_merge_service/api/authentication.py, document_merge_service/api/tests/test_authentication.py, document_merge_service/conftest.py, document_merge_service/settings.py, pytest.ini, requirements.txt
Invalid assumptions has been made that access_token is always a JWT
token. The OpenID specification doesn't require it and only a few
IAM actually implement it that way.
This change has the additional advantage that no crypthography library
is needed within Caluma context which could have vulnerabilities.
=> Use OpenID connect userinfo endpoint to validate bearer token

README.md, document_merge_service/api/authentication.py, document_merge_service/settings.py, pytest.ini
This could be a security issue if in case access token expires before
cache expires. Hence disabled by default but might still be helpful
to cache in case OpenID Connect provider is slow.
=> Make caching of userinfo optional

document_merge_service/api/authentication.py, document_merge_service/api/tests/test_authentication.py
Some token especially of providers which use JWT also for access tokens
are too long for memcache key limit of 250 so the need to be hashed.
=> Use hashsum of token for userinfo caching

.gitignore, document_merge_service/api/tests/test_template.py, document_merge_service/api/views.py
In `TemplateView.merge()` the content_type was written to `response.content` which resulted in broken documents.
Additional change: added `.idea/` to .gitignore.
Closes #72
=> [BUGFIX] write content_type to header

Dockerfile, README.md, docker-compose.override.yml, document_merge_service/api/serializers.py, document_merge_service/api/tests/test_template.py, document_merge_service/api/unoconv.py, document_merge_service/api/views.py, document_merge_service/settings.py, document_merge_service/tests/test_settings.py
This commit implements a way to use the unoconv CLI instead of the
webservice container.
Usage of this is discouraged and only useful if the target platform has
some kind of restrictions about what (and how many) services are allowed
to run.
=> Provide a way to use a local unoconv process

document_merge_service/settings.py
python version may differ in different distributions but it is common
practice to provide python3. This binary will also be local and not overwritten by pyenv or locally
with pyenv so tests can be run locally again.
This fixes issue CI currently not running as docker container updated to
Debian buster.
=> Use python3 binary to run unoconv

README.md, document_merge_service/api/authentication.py, document_merge_service/api/tests/test_authentication.py, document_merge_service/settings.py, requirements.txt
Up to now Document Merge Service only supported authorization through OpenID Connect.
This change allows beside using OpenID Connect as authentication to use any service with a json api to be used as authorization service returning list of groups.
=> Add option to call groups api for authorization

document_merge_service/settings.py
django-environ determines a variable with a leading $ as a proxied environment variables which is not the case in jsonpath hence need to use envrion directly.
=> Do not proxy jsonpath environ value with a leading $

README.md, document_merge_service/api/apps.py, document_merge_service/api/tests/test_template.py
For this to work we simply fallback to icontains. Mysql and Postgres will still use their full text search.
This is a perquisite to get django 2.2 running.
=> Allow search lookup to be used in sqlite

document_merge_service/api/tests/test_template.py, document_merge_service/api/views.py
=> fix: return templates which have no group to everyone

README.md, document_merge_service/api/authentication.py, document_merge_service/api/tests/test_authentication.py, document_merge_service/settings.py
This needs to be split as it is different service with different characteristics.
=> Split re-validation time of token and groups api

docker-compose.override.yml
This makes sure that dev images (with dev deps) aren't used in other
projects that expect "non-dev" images.
=> fix: add "dev" tag for dev images

document_merge_service/settings.py
This commit adds a basic logging config. This makes sure traces get
printed in the uwsgi log.
=> feat(logging): add basic logging config

docker-compose.override.yml, docker-compose.yml
This commit bumps the compose file version from `3` to `3.4`.
=> chore(compose): bump docker-compose file version

Dockerfile, Makefile, README.md, docker-compose.override.yml, docker-compose.yml, document_merge_service/api/serializers.py, document_merge_service/api/tests/test_template.py, document_merge_service/api/tests/test_unoconv.py, document_merge_service/api/unoconv.py, document_merge_service/api/views.py, document_merge_service/settings.py, document_merge_service/tests/test_settings.py, unoconv/Dockerfile
The tfk-api-unoconv webservice was initially added as a convenient way to interact with unoconv. In                                                                                                                                            
the meantime a UNCONV_LOCAL mode was added, to eliminate the dependency on the tfk-api-unoconv                                                                                                                                                 
webservice by running unoconv directly inside the document-merge-service container.                                                                                                                                                            
As a consequence of this new operation mode we had significant performance …
=> feat: Replace tfk-api-unoconv service with unoconv listener

.travis.yml, CHANGELOG.md, document_merge_service/document_merge_service_metadata.py, setup.cfg
Because of various parsing problems of python-semantic-release we decided that
we are no longer going to use it for automatic releases. We will still use it to
generate the rough changelog, which is then manually curated.
Also see:
https://github.com/projectcaluma/caluma/pull/885
=> Release 3.0.0

document_merge_service/api/engines.py, document_merge_service/api/tests/snapshots/snap_test_template.py, document_merge_service/api/tests/test_template.py, document_merge_service/conftest.py
Jinja2 allows more complex syntax than just filling in placeholders. This confused
the validation logic, as Jinja couldn't handle our _MagicPlaceholder in some places.
This solves the problem by inheriting from UserString (basically `str`) and implementing
__radd__(), which implements the operator in question. Note that it possibly will need
more operators, depending on what the templates want to do. There's a parameterizable
test now to validate more expressions as they come up
Fixes #254
=> fix(validation): don't reject templates with complex syntax

.gitlint
This is necessary, because dependabot is not following this convention.
=> chore(CI): ignore body-max-line-length in gitlint

USAGE.md, document_merge_service/api/serializers.py, document_merge_service/api/tests/test_template.py, requirements-dev.txt
Add new parameter `disable_template_validation` on template upload. This
can be used if you cannot provide correct sample data upon upload, and/or
the magic validation does not work.
=> Feat disable test render

document_merge_service/api/tests/test_template.py, document_merge_service/api/unoconv.py, document_merge_service/conftest.py
the subprocess can exit normally but leave orphan forks, so after communicating
with the process, we terminate then kill the whole process-group.
=> fix(subprocess): add timeout and cleanup orphan forks

document_merge_service/api/tests/test_unoconv.py
This test is flaky and blocks our open PRs. We skip it for now to unblock releasing.
Related to #443
=> chore(ci): skip flaky unoconv fork test

document_merge_service/api/data/__init__.py, document_merge_service/api/migrations/0004_cleanup_files.py, document_merge_service/api/models.py, document_merge_service/api/tests/snapshots/snap_test_template.py, document_merge_service/api/tests/test_template.py, document_merge_service/conftest.py, requirements-dev.txt, setup.cfg
=> fix(cleanup): delete old files when template is deleted or changed

document_merge_service/api/serializers.py, document_merge_service/api/tests/test_template.py, document_merge_service/api/urls.py, document_merge_service/api/views.py
A lot of things here only worked accidentally. We need to be more explicit
about the download URL and don't mount the download view in the same place
where the API resides (/api/v1/templates/foo would use the REST endpoint,
while /api/v1/templates/foo.docx would trigger the download of the
template document.)
Now, the template download is found under /api/v1/template-download/(slug),
which separates those concerns. The download URL was also only implicitly
correct and doesn't work if circumstances don't exactly match the expectation.
Non-breaking, as the API now just outputs the new URL, which is the URL
used by the frontend anyway.
=> fix(template): make template download url more stable

document_merge_service/api/serializers.py, document_merge_service/api/tests/test_template.py, document_merge_service/urls.py
The previous change crashed the API in list view if we had any template
with an actual template file attached. Fix this, so that the list
actually returns data as well
=> fix(api): do not crash in list view

document_merge_service/api/migrations/0004_cleanup_files.py
I didn't figure out how to make a log message actually show up in the container logs, so I went for a `pass` statement with a comment instead.
=> fix(cleanup-migration): fail gracefully in new container

document_merge_service/api/management/commands/clean_dangling_files.py, document_merge_service/api/migrations/0004_cleanup_files.py, document_merge_service/api/tests/test_clean_dangling_files.py
The cleanup migration is too dangerous since it will possibly delete production data if something goes wrong. This commit converts the migration to a command which can be called manually and has a dry run option to test it beforehand.
=> fix(cleanup): convert cleanup migration to command

requirements.txt
Django doesn't have a direct dependency to jinja2 anymore but we require it
=> chore(deps): add direct dependency to jinja2

.github/workflows/tests.yml, Dockerfile, document_merge_service/api/views.py, document_merge_service/settings.py
Since we hide /tmp from LibreOffice processes we can't use /tmp for temporary files. I first used `$MEDIA_ROOT/__convert__`, but this directory is not an internal directory as I expected (it was a bad idea), so I moved `__convert__` to /var/lib/document_merge_service/data/tmp ($DATABASE_DIR/tmp). The Dockerfile will set the rights correctly: shared between the dms-user and root.
=> fix: move temporary path to data directory

CONFIGURATION.md, document_merge_service/api/pagination.py, document_merge_service/api/tests/test_pagination.py, document_merge_service/settings.py
This adds the possiblity to configure the pagination via environment variables and query params:
- Add possibility to let the client configure the page size via the `page_size` query param
- Add env var `PAGINATION_ENABLED` to completely disable pagination
- Add env var `PAGINATION_DEFAULT_PAGE_SIZE` to configure the default page size
- Add env var `PAGINATION_MAX_PAGE_SIZE` to configure the max value of the `page_size` query param
=> feat(api): make pagination configurable

CONFIGURATION.md, document_merge_service/settings.py
=> feat: add email error handler

CONFIGURATION.md, document_merge_service/settings.py
As mentioned in https://github.com/adfinis/document-merge-service/pull/575#issuecomment-1375758192
=> fix(settings): enable email settings without email error handler

CONFIGURATION.md, document_merge_service/api/engines.py, document_merge_service/api/management/commands/clean_dangling_files.py, document_merge_service/api/management/commands/upload_local_templates.py, document_merge_service/api/models.py, document_merge_service/api/tests/test_upload_local_templates.py, document_merge_service/conftest.py
because the s3 storage backend doesn't provide absolute paths, only names
add management command to upload local files after a loaddata
=> fix: storage generic file cleanup

CONFIGURATION.md, MIGRATE.md, docker-compose.yml, document_merge_service/extensions/permissions.py, document_merge_service/extensions/visibilities.py, document_merge_service/settings.py
Document Merge Service is not supposed to be run as django application inside of a django project but as standalone docker service. Therefore, it must be completely 12factor compatible. To achieve this, we need to have env vars for permission and visibility classes.
CC @Yelinz
=> fix(dgap): add env variables to configure permissions and visibilities

document_merge_service/api/migrations/0006_remove_template_group.py
This adjustment in the migration will be too late for projects that already ran the migration. However, IMO it's still worth to adjust it so we don't loose any more data.
As we recommend migrating that info into a meta property, we do exactly that in the migration.
=> fix(template): migrate group to meta property before removing

.github/workflows/pypi.yml, .github/workflows/tests.yml, .mypy.ini, CONFIGURATION.md, Makefile, document_merge_service/api/management/commands/dms_encrypt_templates.py, document_merge_service/api/tests/test_encrypt_templates.py, document_merge_service/settings.py, poetry.lock, pyproject.toml
add setting to be able to use SSEC when using the S3 storage backend.
S3 will complain if trying to access encrypted files without a key or unencrypted with a key.
Therefore enabling encryption has to be coupled with a reupload of all files with the correct setting. (management command will do it)
=> feat(s3): add s3 ssec option

poetry.lock, pyproject.toml
This fixes an error that occurs when server-side encryption is enabled and multiple templates are uploaded with the same filename.
=> fix(sse-c): bump django-storages to include fix for head_object

docker-compose.override.yml, docker-compose.yml, document_merge_service/api/serializers.py, document_merge_service/api/tests/test_template.py
Instead of multiple fields with the same name (traditional form-data
lists), we also accept a JSON list for the available placeholders. This
helps reduce the number of fields in the request, which WAF, Django, and
possibly other server-side web components don't appreciate.
=> feat(api): accept available placeholders as json list

.github/workflows/ghcr.yml, .github/workflows/pypi.yml, .github/workflows/tests.yml
ubuntu-latest has recently switched to Ubuntu 24.04, with some breaking changes, among others restricting the creation of namespaces as unprivileged user, but also other compatibility issues within Python itself.
Until this is resolved, we pin the runs to Ubuntu 22.04.
=> Use Ubuntu 22.04 for GitHub actions

poetry.lock
Note that the branch containing this commit has been merged into upstream django-storages via https://github.com/jschneier/django-storages/pull/1451 in the meantime, but did not make it into the 1.14.5 release, which happened 3 days prior to the MR being merged.
=> chore(deps): update django-storages reference after force-push

CHANGELOG.md, pyproject.toml
Contains #956, #957 (and #933, not mentioned in the changelogs, as it only affects the CI pipeline).
=> chore(release): v7.3.6

.github/workflows/ghcr.yml
This addresses the issue of the v7.3.6 release not triggering a container image build.
=> fix(ci): create images also on release drafts being published

.github/workflows/tests.yml, Dockerfile, Makefile, docker-compose.override.yml, poetry.lock, pyproject.toml
BREAKING CHANGE: This will remove poetry entirely from the production
image. If you customized the command, make sure to remove `poetry run`
as the binaries are now globally available without using poetry.
If you installed additional requirements using `poetry install` make
sure to use `pip install` instead.
---
This reduces the production image size from ~1.5GB to ~800MB
=> feat(build): use multi stage docker build for smaller images

.github/workflows/ghcr.yml, .github/workflows/tests.yml, Dockerfile, docker-compose.override.yml, poetry.lock, pyproject.toml
This introduces a `slim` image variant that does not have any extras (PostgreSQL, Memcached, S3) installed. This image can be used in very simple setups or in setups that require other dependencies (e.g. MySQL or Azure Storage).
Resolves #572
---
**Approximal image sizes:**
Full: 813MB
Slim: 780MB
=> feat(docker): add image variants

CHANGELOG.md, pyproject.toml
I accidentally pushed the tag v8.0.1 before I found the `MAINTAINING.md` file :sweat_smile:. Is it ok to just push a tag with the next number?
=> chore(release): v8.0.2
