CONTRIBUTING.md, Dockerfile, Makefile
This allows to install pip for user without having root.
=> Give docker user a home

document_merge_service/api/views.py, document_merge_service/settings.py, requirements.txt
This only works for database engines which support it.
Currently mysql and postgresql.
=> Allow fulltext search on template description

README.md, document_merge_service/settings.py, requirements.txt
Configuration is possible with the env vars:
* CORS_ORIGIN_ALLOW_ALL
* CORS_ORIGIN_REGEX_WHITELIST
Closes #74
=> Add CORS headers

document_merge_service/api/engines.py, document_merge_service/api/tests/test_filter.py
* date
* datetime
* emptystring
Closes #88
=> feat(jinja): add custom filters

requirements-dev.txt, requirements.txt
* Removing pyup pinning
* Pinning pydocstyle as otherwise CI fails
=> Make requirements ready for enabling dependabot

CONFIGURATION.md, README.md, USAGE.md
Extend the user guide and explain how to use the various features of the DMS.
Note: builds on top of #237 so merge that first!
=> Improve docs

CHANGELOG.md, document_merge_service/document_merge_service_metadata.py, requirements-dev.txt, requirements.txt
Bump version, update dependencies while we're at it
=> chore(release): version 4.0.1

USAGE.md, document_merge_service/api/engines.py, document_merge_service/api/tests/snapshots/snap_test_template.py
Additionally there's a commit that fixes the snapshot.
=> chore(docs): clarify image filter usage

document_merge_service/api/tests/test_template.py, document_merge_service/api/views.py
When a template accesses a placeholder that's not present in the
provided data, Jinja raises an exception that ends up as a HTTP/500 in
the response. Instead, we want a (more or less) meaningful HTTP/400 to
be returned.
=> fix(crash): dont crash when accessing undefined value in template

CHANGELOG.md, Dockerfile, document_merge_service/api/test_unoconv.py, document_merge_service/api/unoconv.py, document_merge_service/document_merge_service_metadata.py, requirements-dev.txt
The [functionality](https://github.com/adfinis-sygroup/document-merge-service/pull/390) was already reviewed by `winged`.
=> fix(subproccess): add tests, read uwsgi config and release

document_merge_service/api/engines.py, document_merge_service/api/tests/snapshots/snap_test_template.py, document_merge_service/api/tests/test_template.py
=> fix(jinja): autoescape data passed to template when merging

.github/workflows/tests.yml, .gitignore, .mypy.ini, Dockerfile, Makefile, document_merge_service/api/factories.py, document_merge_service/api/models.py, poetry.lock, pyproject.toml
=> switch to python 3.10 and enable mypy

LICENSE, README.md, pyproject.toml
BREAKING CHANGE: document-merge-service is now released under the GPL-3.0-or-later license.
Resolves #226
=> feat(license): switch license from MIT to GPL-3.0-or-later

document_merge_service/api/engines.py, document_merge_service/api/tests/test_excel.py
Excel template validation needs some more work than expected.
Implement "undefined" handler for Jinja to detect undefined
variables, and use our magic placeholder structure to record
those variable accesses in the template.
Then, we can easily compare available placeholders with the ones
required by the template.
=> fix(validation): fix excel template validation

.github/workflows/pypi.yml, MIGRATE.md, pyproject.toml
fix wrong version number in pyproject
=> chore: introduce pypi workflow

.mypy.ini, document_merge_service/api/filters.py, document_merge_service/api/tests/test_filters.py, document_merge_service/api/views.py
problem in test, when selectivly running tests the settings are overriden and it works. when running the whole test suite the settings arent changed and fails
=> feat(filters): add configurable meta filter

CHANGELOG.md, pyproject.toml
* **settings:** Add s3 ssl settings ([#698](https://github.com/adfinis/document-merge-service/issues/698)) ([`c92b381`](https://github.com/adfinis/document-merge-service/commit/c92b381ce6ebc45c0b96eba828b471f2bd28a169))
=> chore(release): v6.4.4

document_merge_service/api/jinja.py
=> fix: use a sandboxed environment

CHANGELOG.md, pyproject.toml
=> chore(release): v7.3.7

document_merge_service/settings.py
=> fix(settings): make DOCXTEMPLATE_JINJA_EXTENSIONS setting optional
